### ISSUE TITLE
where is the user role getter and setter method ?

### ISSUE THREAD

**Issue by wozaisuzhou** [Yoh0xFF/java-spring-security-example#1]

**Comment by Yoh0xFF** [comment]
Hey I am using the [Lombok library](https://projectlombok.org/), which helps you to automate some of the traditional Java boilerplate.

For example when you annotate a class with the @Data annotation setter/getter functions for private fields are automatically generated:
`
@Data
class User {
  private String firstName;
  private String lastName;
}
`

Hope I understood the question correctly.
