### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Mr-Lei-Xuesong** [Yoh0xFF/java-spring-security-example#8]
Thanks, but what about JwtTokenUtil class? I cannot find it in any library.

**Comment by Yoh0xFF** [comment]
Hi, @Mr-Lei-Xuesong I removed it. I use this dependency instead:

```
<dependency>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-starter-oauth2-resource-server</artifactId>
</dependency>
```

This line of [code](https://github.com/Yoh0xFF/java-spring-security-example/blob/68cb5f8af40bfe18bbaaafa0b59c46d46316d1d4/src/main/java/io/example/configuration/SecurityConfig.java#L116) automatically registers the filter, which does the JWT token validation.

**Comment by uniquejava** [comment]
I am also curious, and here is the removed JwtTokenUtil 👍  : https://github.com/Yoh0xFF/java-spring-security-example/blob/d99882f896d9eb95e885233c1e2bbb4de9cd749f/src/main/java/io/example/configuration/security/JwtTokenUtil.java
